"""add image_path to publication model

Revision ID: 9689e7f1e78e
Revises: 20cb0d74bd09
Create Date: 2025-12-14 21:47:26.977257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9689e7f1e78e'
down_revision: Union[str, Sequence[str], None] = '20cb0d74bd09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'image_path')
    # ### end Alembic commands ###
