"""Add show_in_cv fields to Education, Experience, Award, Publication

Revision ID: c4d5e6f7a8b9
Revises: b3c1d2e4f5a6
Create Date: 2026-04-18 00:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'c4d5e6f7a8b9'
down_revision: Union[str, Sequence[str], None] = 'b3c1d2e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# 원본 CV 페이지에 있던 12개 논문 제목
CV_PUBLICATION_TITLES = [
    "Wide-field-of-view, switchable, multi-dimensional light-field display using a metasurface lenticular lens",
    "300 units per second roll-to-roll manufacturing of visible metalenses",
    "Scalable manufacturing of high-index atomic layer-polymer hybrid metasurfaces for metaphotonics in the visible",
    "Roll-to-plate printable RGB achromatic metalens for wide-field-of-view holographic near-eye display",
    "Full-color augmented reality near-eye displays using single-layer achromatic metasurface waveguides",
    "A water-soluble label for food products prevents packaging waste and counterfeiting",
    "Anti-aliased metasurfaces beyond the Nyquist limit",
    "Polariton condensate far-detuned from exciton resonance in WS2 bound states in the continuum",
    "Amorphous to crystalline transition in nanoimprinted sol-gel titanium oxide metasurfaces",
    "Dynamic hyperspectral holography enabled by inverse-designed metasurfaces with oblique helicoidal cholesterics",
    "Multicolor and 3D holography generated by inverse-design single-cell metasurfaces",
    "Metasurfaces-driven hyperspectral imaging via multiplexed plasmonic resonance energy transfer",
]


def upgrade() -> None:
    op.add_column('education', sa.Column('show_in_cv', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('experience', sa.Column('show_in_cv', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('award', sa.Column('show_in_cv', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('publication', sa.Column('show_in_cv', sa.Boolean(), nullable=False, server_default='false'))

    # 기존 education/experience/award 레코드는 모두 CV에 표시
    op.execute("UPDATE education SET show_in_cv = TRUE")
    op.execute("UPDATE experience SET show_in_cv = TRUE")
    op.execute("UPDATE award SET show_in_cv = TRUE")

    # 원본 CV에 있던 12개 논문만 show_in_cv=True
    for title in CV_PUBLICATION_TITLES:
        op.execute(
            sa.text("UPDATE publication SET show_in_cv = TRUE WHERE title = :title"),
            {"title": title},
        )


def downgrade() -> None:
    op.drop_column('publication', 'show_in_cv')
    op.drop_column('award', 'show_in_cv')
    op.drop_column('experience', 'show_in_cv')
    op.drop_column('education', 'show_in_cv')
